設定変更

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -68,6 +68,10 @@ jobs:
         with:
           name: build
 
+      - name: Verify Dist Directory
+        run: |
+          if [ -d "./dist" ]; then echo "dist directory exists"; else echo "dist directory is missing"; exit 1; fi
+
       - name: make FIREBASE_KEY
         run: |
           echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
